/*
 * Copyright (c) 2020 - present Cloudogu GmbH
 *
 * This program is free software: you can redistribute it and/or modify it under
 * the terms of the GNU Affero General Public License as published by the Free
 * Software Foundation, version 3.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Affero General Public License for more
 * details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program. If not, see https://www.gnu.org/licenses/.
 */

package com.cloudogu.repositoryavatar;

import sonia.scm.repository.Repository;
import sonia.scm.repository.RepositoryCoordinates;
import sonia.scm.store.DataStore;
import sonia.scm.store.DataStoreFactory;

import jakarta.inject.Inject;

public class AvatarStore {

  private static final String STORE_NAME = "repository-avatar";

  private final DataStoreFactory dataStoreFactory;

  @Inject
  public AvatarStore(DataStoreFactory dataStoreFactory) {
    this.dataStoreFactory = dataStoreFactory;
  }

  public Avatar getAvatar(RepositoryCoordinates repository) {
    return createDataStore(repository).getOptional(STORE_NAME).orElse(Avatar.autoGenerated());
  }

  public void saveAvatar(Repository repository, Avatar avatar) {
    DataStore<Avatar> dataStore = createDataStore(repository);
    dataStore.clear();
    dataStore.put(STORE_NAME, avatar);
  }

  private DataStore<Avatar> createDataStore(RepositoryCoordinates repository) {
    return dataStoreFactory.withType(Avatar.class)
      .withName(STORE_NAME)
      .forRepository(repository.getId())
      .build();
  }
}
