/*
 * Copyright (c) 2020 - present Cloudogu GmbH
 *
 * This program is free software: you can redistribute it and/or modify it under
 * the terms of the GNU Affero General Public License as published by the Free
 * Software Foundation, version 3.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Affero General Public License for more
 * details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program. If not, see https://www.gnu.org/licenses/.
 */

package com.cloudogu.repositoryavatar;

import lombok.Getter;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlRootElement;

@XmlRootElement
@XmlAccessorType(XmlAccessType.FIELD)
@Getter
public class Avatar {

  private AvatarType type;
  private String iconName;
  private String color;
  private byte[] image;
  private String mediaType;

  Avatar() {
    this.type = AvatarType.AUTO_GENERATED;
  }

  private Avatar(String iconName, String color) {
    this.type = AvatarType.PREDEFINED;
    this.iconName = iconName;
    this.color = color;
  }

  private Avatar(byte[] image, String mediaType) {
    this.type = AvatarType.UPLOADED;
    this.image = image;
    this.mediaType = mediaType;
  }

  static Avatar autoGenerated() {
    return new Avatar();
  }

  static Avatar predefined(String iconName, String color) {
    return new Avatar(iconName, color);
  }

  static Avatar uploaded(byte[] image, String mediaType) {
    return new Avatar(image, mediaType);
  }
}
